### ISSUE TITLE
[NEW] Support collapse/uncollapse quotes, replies and long text attachments

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#1076]
Your Rocket.Chat.Android version: 2.0.0 beta 6

Quoted messages are cut off after certain count of characters which at times make it difficult to read messages which are coming via webhooks. For example, comments on issues from GitLab etc.

![screenshot_20180412-211950_rocketchat](https://user-images.githubusercontent.com/1280585/38680007-d444b800-3e97-11e8-9b97-555734bb2b99.jpg)

@rafaelks

**Comment by rafaelks** [comment]
@mmarif4u This one is addressed already in `develop-2.x` branch. 👍

**Comment by mmarif4u** [comment]
@rafaelks thanks for the info. Is the PR merged or still open?

**Comment by rafaelks** [comment]
@mmarif4u It's merged already. 👍

**Comment by mmarif4u** [comment]
Hi @rafaelks, i am on rc1 now and i still see the same cut off messages. You can check the channel i shared with you via DM. Let me know if you need more info.

**Comment by leonardoaramaki** [comment]
@mmarif4u the reply/quote is cut off or the message is cut off?

**Comment by mmarif4u** [comment]
@leonardoaramaki from the picture above it looks like quotes in the message is cut off. As most of these messages are coming via webhooks as quoted messages. I can provide more details if need to via DM if you want check it on our server.

**Comment by leonardoaramaki** [comment]
@mmarif4u I see. The issue @rafaelks is talking about and yours are different ones.
As I suspected before from your pictures it's coming from bot and treated as quotes as you said. 
The quote being cut off was intended behavior to reduce the noise on the chat but as it seems we didn't count on webhooks messages.
Anyway we're going to address this soon probably by making collapsable/expandable quotes.

**Comment by mmarif4u** [comment]
@leonardoaramaki yes, you are right. Its from bot.
I understand sometime it would be considered noise. But at times, like comments on issues(mostly we use RC to check while out, coming through bots) are helpful to read straight away instead of going to GitLab interface in this case.

I appreciate considering this to implement even if collapsible/expandable. :+1:

**Comment by rafaelks** [comment]
@mmarif4u Can you please confirm if this is still happening in 2.1.0?

**Comment by mmarif4u** [comment]
Yes, its still there in 2.1.0.

**Comment by GezimSejdiu** [comment]
Hi there,
the same cut off or even worst is happening with Trello webhook integrations. 

Please, have a look at the images below for more info: 

**How it is shown on Android app**
![rc_android](https://user-images.githubusercontent.com/5259296/40254842-48edb314-5ae5-11e8-9d74-62b38618cd09.png)

**How it is shown on Rocket.Chat desktop app**
![rocket chat](https://user-images.githubusercontent.com/5259296/40254868-645edf06-5ae5-11e8-8bf2-d1916383d24f.png)

### **Server Setup Information**:
Rocket.Chat Server: 0.64.1
Operating System: Linux

### **Mobile device model and OS version**: 
* Google Pixel 2 - Android 8.1.0

Best regards,

**Comment by mmarif4u** [comment]
@leonardoaramaki any updates on this?.

Also links are now shown as attachments which can be seen above. This was introduced in 2.1.0 while i guess enhancing the file objects.

**Comment by leonardoaramaki** [comment]
@mmarif4u it's on our queue of tasks, but we haven't started fixing this yet. I appreciate your patience anyhow. This issue is already on our roadmap.

**Comment by leonardoaramaki** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/1695

**Comment by mattronix** [comment]
Hi Guys,

This is still an issue :( 

Any tips you can give on how to fix or if an option exists to disable?

We see it happens on phones with a slightly lower resolution.
