### ISSUE TITLE
Issues resuming from background

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#137]
Still working to identify this.  But when resuming from background, often it does not seem to get latest on the current channel in focus.

For example, if i'm having a one on one conversation and put in the background and I get a notification of a new message and restore from background (not tap notification.  That action does seem to work) the latest messages are not loaded.

This seems to happen more when its been backgrounded longer.  Usually to get around this I swipe it away from recents and re-open.  Most of the time this does the trick.  Others I've had to force stop and then open again.

Its un-clear if it simply hasn't established a connection to the server again, or is just failing to load those missed messages.

Might be related to #117 its hard for me to be certain

**Comment by YusukeIwaki** [comment]
It is caused by the state mismatch of ServerConfig model and RocketChatWebSocketThread...
By killing the RocketChatService manually (swipe away from recent tasks), the state is reset and works as expected.

It is really should be fixed..

**Comment by cheonjoosung** [comment]
I tested this issue (related #117) both demo.rocket.chat server & my own rocket server. Surpringly, the problem didn't happen in demo.rocket.chat server almostly.
But, the problem happen frequently in my own server.

**Comment by YusukeIwaki** [comment]
The root cause is that `RxWebSocket#isConnected()` returns true unexpectedly, even after the WebSocket connection is disconnected silently for some reason...

https://github.com/RocketChat/Rocket.Chat.Android/blob/develop/android-ddp/src/main/java/chat/rocket/android_ddp/rx/RxWebSocket.java

**Comment by laggedHero** [comment]
We have an issue to redo the connectivity. Please follow #147

**Comment by geekgonecrazy** [comment]
I know #170 is where redirected to.  But it was closed and still seeing this

Tons of issues resuming from background and it not updating channel until I switch to a new channel and back, also going on mobile network where signal is not great.

I'll be in DM with a user, send to background get a push notification, resume and the message isn't there, have to switch channels and then back and message appears.  

Other times will be in conversation and they will send a message and it'll show in sidebar a new message but won't show in channel pane.  I have to again switch channels and back to get it to show up.

**Comment by laggedHero** [comment]
@YusukeIwaki do you think you may that care of this one?

**Comment by YusukeIwaki** [comment]
```
3:54:49.169 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-4"]
02-05 23:54:49.170 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@c20090d
02-05 23:54:49.350 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-1"]
02-05 23:54:49.351 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@6ab9ed3
02-05 23:54:49.387 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-2"]
02-05 23:54:49.388 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@5512909
02-05 23:54:50.171 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-3"]
02-05 23:54:50.172 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@9cf45a0
02-05 23:54:50.230 D/RoomFragment( 2286): hasNext: true syncstate: 0
02-05 23:54:50.352 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-4"]
02-05 23:54:50.352 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@d655af5
02-05 23:54:50.389 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-1"]
02-05 23:54:50.389 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@88e7d30
02-05 23:54:50.528 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat")
02-05 23:54:50.528 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@6e984b5
02-05 23:54:51.173 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-2"]
02-05 23:54:51.173 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@80266bb
02-05 23:54:51.353 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-3"]
02-05 23:54:51.353 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@6fab731
02-05 23:54:51.390 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-4"]
02-05 23:54:51.391 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@1e6b397
02-05 23:54:51.530 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-1"]
02-05 23:54:51.531 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@712956d
02-05 23:54:52.175 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-2"]
02-05 23:54:52.177 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@158f233
02-05 23:54:52.358 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-3"]
02-05 23:54:52.359 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@d501b69
02-05 23:54:52.393 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-4"]
02-05 23:54:52.394 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@4a67e8f
02-05 23:54:52.534 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-1"]
02-05 23:54:52.535 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@8c60525
02-05 23:54:53.179 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-2"]
02-05 23:54:53.181 V/RocketChatService( 2286): ⇠ getOrCreateWebSocketThread [0ms] = rx.Single@79674ab
02-05 23:54:53.362 V/RocketChatService( 2286): ⇢ getOrCreateWebSocketThread(hostname="demo.rocket.chat") [Thread:"RxComputationScheduler-3"]
```

It seems that `getOrCreateWebSocketThread` doesn't work as expected.
The error handling of `DDPClient#connect` is not good.
I will try to fix it.

**Comment by laggedHero** [comment]
#196 has added up to fixes here.

`Other times will be in conversation and they will send a message and it'll show in sidebar a new message but won't show in channel pane. I have to again switch channels and back to get it to show up.`

Should be fixed.

**Comment by geekgonecrazy** [comment]
@laggedHero awesome!  I'll test the new builds!

**Comment by notfixingit3** [comment]
Still having this issue with 1.0.15 from the play store fyi

**Comment by rafaelks** [comment]
I believe this is fixed already in 1.0.21.
