### ISSUE TITLE
expected END_OBJECT but was NAME at path 

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.Android#2223]
## Issue 

After upgrade to v1.0.0-develop today the Android app throws this error when entering a particular channel.

This particular channel had used the new Reply/Thread function. I then tried a reply in another channel but it didn't break so presumably not related.

Tried upgrading the app to Beta but it still throws the error.

`com.squareup.mosi.jsonDataException: expected END_OBJECT but was NAME at path $.messages[12].reactions.:grin:.usernames at $.messages[12].reactions.:grin:.usernames`

## To Reproduce
Logout, clear cache, login

Go to channel

Above error thrown.

Update to Beta app.

Same issue.

Log on channel access:

```
API ➔ debug GET: /api/v1/groups.roles?roomName=smestuff
Meteor ➔ method getRoomRoles -> userId: hYHbjXWQMSRMu2szG , arguments:  [ 'NpatrG7JMmTZTaHiz' ]
API ➔ debug Success { statusCode: 200,
  body: { roles: [ [Object] ], success: true } }
API ➔ debug GET: /api/v1/commands.list?offset=0&count=100
API ➔ debug Success { statusCode: 200,
  body: 
   { commands: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     offset: 0,
     count: 23,
     total: 23,
     success: true } }
API ➔ debug GET: /api/v1/groups.messages?roomId=NpatrG7JMmTZTaHiz&offset=0&count=30
API ➔ debug Success { statusCode: 200,
  body: 
   { messages: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     count: 30,
     offset: 0,
     total: 7524,
     success: true } }
Meteor ➔ method UserPresence:away -> userId: hYHbjXWQMSRMu2szG , arguments:  [ null ]


```

**Comment by andypost** [comment]
Confirm it, started to get this error after server upgrade to rc.2

**Comment by andypost** [comment]
Some chats can't display messages because of that

**Comment by reetp** [comment]
Just update to todays docker rocketchat:develop and it has gone and I can get back in to the channel again

Please test and see what happens.

**Comment by andypost** [comment]
Just checked update and still can't see chat messages, when I opening chat I getting this
![unnamed](https://user-images.githubusercontent.com/73713/56164958-76abf180-5fda-11e9-8798-f3d80886ff0a.jpg)

**Comment by hypery2k** [comment]
same error here:

```
04-18 05:00:17.423 26923 27172 D AppModule$provideHttpLo: <-- END HTTP (48695-byte body)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: Error refreshing chatrooms
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: chat.rocket.common.RocketChatInvalidResponseException: com.squareup.moshi.JsonDataException: Expected END_OBJECT but was NAME at path $.update[10].lastMessage.reactions.:croissant:.usernames at $.update[10].lastMessage.reactions.:croissant:.usernames(url='https://rocket..../api/v1/rooms.get')
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.internal.rest.RestClientKt.handleResponse(RestClient.kt:86)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.internal.rest.RestClientKt.handleRestCall(RestClient.kt:141)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.internal.rest.RestClientKt$handleRestCall$1.invokeSuspend(RestClient.kt)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: Caused by: com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: Expected END_OBJECT but was NAME at path $.update[10].lastMessage.reactions.:croissant:.usernames at $.update[10].lastMessage.reactions.:croissant:.usernames
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:94)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.model.KotshiMessageJsonAdapter.fromJson(KotshiMessageJsonAdapter.java:283)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.model.KotshiMessageJsonAdapter.fromJson(KotshiMessageJsonAdapter.java:25)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.model.KotshiRoomJsonAdapter.fromJson(KotshiRoomJsonAdapter.java:188)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.model.KotshiRoomJsonAdapter.fromJson(KotshiRoomJsonAdapter.java:22)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.internal.RoomListAdapter.fromJson(RoomListAdapter.kt:36)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.internal.RoomListAdapter.fromJson(RoomListAdapter.kt:22)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.internal.RestMultiResult$MoshiJsonAdapter.fromJson(RestMultiResult.java:67)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.internal.RestMultiResult$MoshiJsonAdapter.fromJson(RestMultiResult.java:47)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:36)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.internal.rest.RestClientKt.handleResponse(RestClient.kt:82)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	... 7 more
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: Caused by: com.squareup.moshi.JsonDataException: Expected END_OBJECT but was NAME at path $.update[10].lastMessage.reactions.:croissant:.usernames
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at com.squareup.moshi.JsonUtf8Reader.endObject(JsonUtf8Reader.java:178)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at chat.rocket.core.internal.ReactionsAdapter.fromJson(ReactionsAdapter.kt:37)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:335)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at com.squareup.moshi.AdapterMethodsFactory$4.fromJson(AdapterMethodsFactory.java:233)
04-18 05:00:17.434 26923 27326 D ChatRoomsViewModel$fetc: 	at com.squareu
```

I think the error is somewhere here: https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/master/core/src/main/kotlin/chat/rocket/core/model/Reactions.kt

This data leads to an error:

```
"reactions":{":croissant:":{"usernames":["testuser","testuser3","testuser2"],"names":["My Testuser","My Testuser 3","My Testuser2"]},":first_place:":{"usernames":["testuser4","testuser5","testuser6","testuser7"],"names":["My Testuser 4","My Testuser 5","My Testuser 6","My Testuser 7"]}}
```

**Comment by hypery2k** [comment]
seems it's an server issue. The data structure is not correct from the backend. I tried with develop and it worked. Seems to be same API error in the backend.

What's interesting: The iOS Mobile App is still working and can handle this kind of an issue

**Comment by andypost** [comment]
rc.3 does not work, as I see broken chats actively using threads and new replies

**Comment by reetp** [comment]
> rc.3 does not work, as I see broken chats actively using threads and new replies

I am currently using Android 3.4 Beta and I don't get the errors on rc3 now.

The chats/replies don't work correctly - but this is on the roadmap for 3.5.0 I believe (they are still fixing the new threading in rocket itself) and is a different bug.

I'd say the original error was fixed and this can probably be closed now - wish I knew which PR fixed it to cross reference.

**Comment by hypery2k** [comment]
how can i get access to the beta release?

**Comment by andypost** [comment]
Just checked and it fails on
- android client 3.4.0 (2062) *beta channel*
- server 1.0.2

**Comment by andypost** [comment]
Today RC app upgraded back to 3.3.1 and after settings reset all chats accessible again

**Comment by Crazy-Hopper** [comment]
I have just upgraded to 3.3.1 (build 2064), reset all data, but the error is still there.

**Comment by philipbrito** [comment]
Guys, this bug was [fixed](https://github.com/RocketChat/Rocket.Chat.Android/pull/2280).
Thanks for posting the logs/JSON here (c/c @reetp @hypery2k).
I'm closing this issue.

**Comment by philipbrito** [comment]
@Crazy-Hopper Are you still getting the same error? 🤔

**Comment by Crazy-Hopper** [comment]
Uhm... sorry for misleading. No, my error is not about name, it just states "Sorry, an error has occured, please try again" upon logging in and no chats are displayed.

**Comment by philipbrito** [comment]
@Crazy-Hopper What is your server version? Is the real name setting enabled for that server?

**Comment by Crazy-Hopper** [comment]
It started after upgrading to 1.x, and now it's latest 1.0.2.
Yes, real names setting is enabled.

**Comment by ChrissW-R1** [comment]
> It started after upgrading to 1.x, and now it's latest 1.0.2.
> Yes, real names setting is enabled.

Same here. Approx. a third of our users have the same issue and can't use the Android app.

**Comment by ChrissW-R1** [comment]
This issue ist closed.
The other one is here: #2308
