### ISSUE TITLE
Rocket Chat 3.3.0 for android crashes down when trying to start video calls

### ISSUE THREAD

**Issue by horvan** [RocketChat/Rocket.Chat.Android#2245]
![Screenshot_20190420-001717](https://user-images.githubusercontent.com/5676367/56446289-31513200-6302-11e9-82b1-59cd89e144de.png)
![Screenshot_20190420-001836](https://user-images.githubusercontent.com/5676367/56446290-31513200-6302-11e9-85bf-f9c91e40e0b5.png)
![Screenshot_20190419-214303](https://user-images.githubusercontent.com/5676367/56446303-462dc580-6302-11e9-9fe4-f8748bd1399c.png)

## Describe the bug

Rocketchat 3.3.0 for androied crashes down when trying to start video calls
## To Reproduce

App shouldn't crash and reopen
## Screenshots

attatched## Devices and Versions

Your Rocket.Chat.Android version: 3.3.0
Your Rocket.Chat Server version: 0.73.1

Qubot X 18_Plus
Android 8.0.0
## Additional context
Filed a bug report with android, too for you to see the system information file send with this report.
.

**Comment by lorek123** [comment]
Check camera permissions, this should be fixed either way, but at least it will be usable until then

**Comment by Adizbek** [comment]
Thanks for submitting issue, I'll look at it today.

**Comment by Adizbek** [comment]
@horvan Can you try version 3.4.0?

**Comment by horvan** [comment]
@Adizbek  Is this available with beta program in android store, already?

**Comment by Adizbek** [comment]
@horvan Yes, It has been released recently, added many new features.  but it is still buggy. avatars not loading.

**Comment by Adizbek** [comment]
@horvan I m sorry. It is not in Play Store. I don't know why. 

But Android team said they had released.


![](https://i.imgur.com/0ZBYIYx.png)

**Comment by Adizbek** [comment]
@horvan my apologies again, yes it's available in beta program. just checked.

**Comment by horvan** [comment]
Works since server is updated to 1.01
