### ISSUE TITLE
Update from 3.5.0 to 3.5.1 fails

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Android#2461]
## Describe the bug

Update from 3.5.0 to 3.5.1 fails on Android 7.1.1 and Android 9.0. I've seen this bug on two different mobiles and Android versions.

## To Reproduce
Try to update via Play Store from 3.5.0 to 3.5.1.

## Expected behavior
Update to 3.5.1.

## Screenshots

![Screenshot_20190821-101801](https://user-images.githubusercontent.com/8544984/63449915-402b2b00-c441-11e9-9d29-3caa646324d3.png)

## Devices and Versions

Your Rocket.Chat.Android version: 3.5.0 -> 3.5.1
Mobile device model and OS version:  Aquaris X5 Plus, Android 7.1.1 and OnePlus 7 Pro, Android 9.0

**Comment by Sing-Li** [comment]
@localguru  known problem.   You should see the bad image size of 8 MB.   Should be fixed shortly.  Thanks for the report.

**Comment by localguru** [comment]
@Sing-Li yes, 8 MB size. I deinstalled and reinstalled (~ 56 MB), that worked.

**Comment by philipbrito** [comment]
@localguru We're sorry for the inconvenience! We have introduced a break change that keeps the users unable to upgrade the app. The way to go is really uninstalling the app and downloading it again. The good news is that besides the bugs fixes and improvements we have done the app size is now much smaller than the older versions (from ˜60mb to up to 30MB now). 
Thanks for your comprehension.

**Comment by agargiulo** [comment]
I'm still unable to update but the update size is not the same as the previous update which errored out. First showed about 8MB and this one is around 24MB. I can look at adb logs later maybe but I'd rather not have to reinstall the app in order to update it.
* edit. Version I'm on: 3.5.0 updating to 3.5.1

**Comment by Sing-Li** [comment]
Please see our post mortem resolution:

https://forums.rocket.chat/t/android-app-3-5-1-update-issue-post-mortem/4422
